"""Initial database schema

Revision ID: 7ccd90925c99
Revises: 
Create Date: 2025-03-31 16:37:44.448987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ccd90925c99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_games_game_id'), 'games', ['game_id'], unique=False)
    op.alter_column('leagues', 'season',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.create_index(op.f('ix_leagues_league_id'), 'leagues', ['league_id'], unique=False)
    op.alter_column('player_stats', 'fp',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(precision=5, asdecimal=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.create_index(op.f('ix_player_stats_stat_id'), 'player_stats', ['stat_id'], unique=False)
    op.alter_column('players', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint('players_team_id_jersey_number_key', 'players', type_='unique')
    op.create_index(op.f('ix_players_player_id'), 'players', ['player_id'], unique=False)
    op.alter_column('teams', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_teams_team_id'), 'teams', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_team_id'), table_name='teams')
    op.alter_column('teams', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_players_player_id'), table_name='players')
    op.create_unique_constraint('players_team_id_jersey_number_key', 'players', ['team_id', 'jersey_number'])
    op.alter_column('players', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_player_stats_stat_id'), table_name='player_stats')
    op.alter_column('player_stats', 'fp',
               existing_type=sa.Float(precision=5, asdecimal=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_index(op.f('ix_leagues_league_id'), table_name='leagues')
    op.alter_column('leagues', 'season',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_games_game_id'), table_name='games')
    # ### end Alembic commands ###
